# Training Configuration
# about 46M param
# Total Parameters: 45,930,574
# Trainable Parameters: 45,930,566
#   pointnet_encoder: 10,834,944 params (23.59% of total)
#   scene_transformer: 12,617,732 params (27.47% of total)
#   ray_encoder: 3,540,992 params (7.71% of total)
#   predictor: 18,935,882 params (41.23% of total)
#     dpt_head: 6,314,051 params (13.75% of total)

# Training: 
# Model: 
# --  Using chunked h5 --> mainly evaluating this for training speed
# --  new encoder structure: materials go into pointnet too, gets rid of old mlp branch + fusion approach 
#     -- frees up enough ~100K params for another hidden dim in pointnet
# --  uses OBB-based RoPE
# --  use 2 register tokens
# --  using param split that allocates 50% of params to encoder, moved some capacity from predictor to the encoder.
# Data: attempt6_table_chair_540 -- 5k epochs 
# -- compare with attempt6_table_chair_540/20260630-164755_full_ds_params46M_regtokens2 (same but uses rope_centroid)

encoder:
  input_dim: 16  # Position (x,y,z) + Normal (nx,ny,nz) + Material (10)
  hidden_dims: [512, 768, 1024, 1536]
  output_dim: 512
  backbone_dim: 768
  pooling_type: 'hierarchical' # 'hierarchical' 'max' or 'local_features'
  num_hierarchical_levels: 3 # Ignored when using local features
  use_local_patches: false

decoder:
  hidden_dim: 512
  ffn_hidden_dim: 2048 # 512 * 4???
  num_layers: 4 
  num_heads: 4
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true # Whether to double the max frequency for RoPE.
  norm_type: 'layer_norm'
  qk_norm: true
  bias: true
  rope_double_max_freq: false
  num_register_tokens: 2

ray_encoder:
  pe_type: 'rope_obb' # RoPE handles spatial position encoding. Options: 'rope_centroid' (3D centroid), 'rope_obb' (12D OBB)
  vertex_pe_num_freqs: 8 # this controls how many frequencies are applied for the pe
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 4
  patch_size: 16
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 512 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  # TODO: add a obj num_freq term?
  hidden_dim: 512
  ffn_hidden_dim: 1024
  num_layers: 4
  num_heads: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'
  pe_type: 'rope_obb' # Options: 'rope_centroid' (3D centroid), 'rope_obb' (12D OBB), 'nerf'
  pe_num_freqs: 8 # is this redunant to vertex_pe_num_freqs? TODO: figure this out 
  use_dpt_decoder: true
  dpt_features: 128
  dpt_out_channels: [64, 128, 256, 512] 
  include_alpha: false

training:
  batch_size: 10 #64
  learning_rate: 1.0e-4
  num_epochs: 20000
  warmup_epochs: 2000
  save_interval: 250  # for visualization
  checkpoint_interval: 2000  # for saving model checkpoint 
  image_res: 128
  data_dir: "renderformer/datasets/processed_datasets/ds2_chairs1-3_cbox0-3"
  log_dir: "training/logs/rf_ds2_chairs1-3_cbox0-3"
  run_name: "full_ds_params46M_unified_encoder_ropeOBB_regtokens2" # Optional string tag for log dir name
  # max_dataset_size: 10   # Optional max samples for dataset
  # shuffle_data: true
  # shuffle_data_seed: 42
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
  use_amp: True
  use_compile: False
  package_model: True
  num_workers: 16