# Training Configuration
# about 46M param --- 
# WAIT THIS IS UNIDEAL - WE WANT HEAVIER ENCODER LIGHTER PREDICTOR DON'T WE
# Total Parameters: 46,232,462
# Trainable Parameters: 46,232,454
#   pointnet_encoder: 7,491,584 params
#   scene_transformer: 7,104,004 params
#   ray_encoder: 2,655,744 params
#   predictor: 28,981,130 params
#     dpt_head: 10,042,243 params

# Training: test small set overfitting ability
# Model: using new model with no state manager
# -- fixed rope dims, fixed ray dirs in camera space
# Sample 4 from attempt6_table_chair_540, shuffle using seed 43
# 10k epochs

encoder:
  input_dim: 6  # Position (x,y,z) + Normal (nx,ny,nz)
  hidden_dims: [1024, 1024, 2048]
  output_dim: 384
  backbone_dim: 512
  property_embed_dim: 128
  pooling_type: 'hierarchical' #'local_features' # Replaced 'hierarchical' and 'max' with set abstraction for local features
  num_hierarchical_levels: 3 # Ignored
  use_local_patches: false
  # num_centroids: 64

decoder:
  hidden_dim: 384
  num_layers: 4 
  num_heads: 4
  feedforward_dim: 1536 # 512 * 4??? The number of frequencies in the positional encoding for vertex positions
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true # Whether to double the max frequency for RoPE.
  norm_type: 'layer_norm'
  qk_norm: true
  bias: true
  rope_double_max_freq: false
  num_register_tokens: 0

ray_encoder:
  pe_type: 'rope_centroid' # RoPE handles spatial position encoding. Options: 'rope_centroid' (3D centroid), 'rope_obb' (12D OBB)
  vertex_pe_num_freqs: 8 # this controls how many frequencies are applied for the pe
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 4
  patch_size: 16
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 384 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  # TODO: add a obj num_freq term?
  hidden_dim: 384
  num_layers: 8
  num_heads: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'
  pe_type: 'rope_centroid' # Options: 'rope_centroid' (3D centroid), 'rope_obb' (12D OBB), 'nerf'
  pe_num_freqs: 8 # is this redunant to vertex_pe_num_freqs? TODO: figure this out 
  use_dpt_decoder: true
  dpt_features: 128
  dpt_out_channels: [96, 192, 384, 768] 
  include_alpha: false

training:
  batch_size: 64
  learning_rate: 1.0e-4
  num_epochs: 10000
  warmup_epochs: 1000
  save_interval: 100  # for visualization
  checkpoint_interval: 1000  # for saving model checkpoint 
  image_res: 128
  data_dir: "data_generation/output_auto/datasets/attempt6_table_chair_540"
  log_dir: "training/logs/attempt6_table_chair_540"
  run_name: "overfit_n4_shuffleseed43_epochs10k" # Optional string tag for log dir name
  max_dataset_size: 4   # Optional max samples for dataset
  shuffle_data: true
  shuffle_data_seed: 43
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
  use_amp: True
  use_compile: False
  package_model: False
