# Training Configuration

# Run notes (changes from last run): training loss
# Model: 
#
# Dataset: using ~1k points shapenet objects dataset: 
#     data_generation/output/datasets/shapenet_take3_table_vessel_chair_guitar_motorbike_car_airplane
# Hyperparams: batch size 64
# Training: 
#   change loss to follow renderformer:
#   change to L1 loss instead of L2
#   apply log transform for L1 input and tone-mapping for lpips input as per renderformer

encoder:
  input_dim: 6  # Position (x,y,z) + Normal (nx,ny,nz)
  hidden_dims: [512, 1024, 2048] # Increase capacity for memorization
  output_dim: 1024 # Increased
  backbone_dim: 1024
  pooling_type: 'hierarchical' # Simpler than hierarchical for pure memorization
  num_hierarchical_levels: 3 # Ignored

state:
  num_tokens: 216  # 8x8x8 grid
  token_dim: 1024 # Match encoder output
  learnable_init: true
  init_scale: 0.1

decoder:
  hidden_dim: 1024
  num_layers: 4 # Slightly deeper
  num_heads: 8
  feedforward_dim: 2048
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true
  norm_type: 'layer_norm'
  qk_norm: false
  num_register_tokens: 0

ray_encoder:
  pe_type: 'nerf' # simpler than rope for ray queries initially
  vertex_pe_num_freqs: 8
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 8
  patch_size: 8
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 1024 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  hidden_dim: 1024
  num_heads: 8
  num_layers: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'

training:
  batch_size: 64
  learning_rate: 1.0e-4
  num_epochs: 500
  save_interval: 50
  image_res: 256
  data_dir: "data_generation/output/datasets/shapenet_take3_table_vessel_chair_guitar_motorbike_car_airplane"
  log_dir: "training/logs"
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
