# Training Configuration
# reduce model size significantly: 30.5M params
# these are same params as very initial model runs

# Training: 
# --> Using new dataset: attempt6_table_chair_540
#   -> try training at 256x256 resolution with patch size 8 now#   use new dpt head implementation on predictor, increase to 4 layers in predictor for dpt compatibility
#   Add norm layer in predictor stage between transformer and output projection, to match renderformer implementation 
#   Use linear warmup and cosine annealing on LR


# ---------
# Run notes (changes from last run): 
#     Updated/fixed RoPE implementation in MHA
#     Using 64 local pointnet features (set abstraction: for 2048 points pershape, 64 centroids each feature is avg of 32 points) 
#
#     Switch to ROPE for predictor. Refactored to use new transformer modules.
#     Reduce state size to 2x2x2 grid
#     Attempted to implement View-dependent stage in camera space
# Model: 
#     Rays now encoded in camera space (so view-dependent stage is now in camera coordinates)
#     Obj positions also transformed to camera space in RadiancePredictor
#     In RayEncoder, remove 2D Patch Positional Encodings, so that encoder matches ViewTransformer of RenderFormer
# Dataset: variable_camera_experiment
#     data_generation/output/datasets/variable_camera_experiment
# Hyperparams:


encoder:
  input_dim: 6  # Position (x,y,z) + Normal (nx,ny,nz)
  hidden_dims: [128, 256, 512]
  output_dim: 512
  backbone_dim: 512
  pooling_type: 'hierarchical' #'set_abstraction' # Replaced 'hierarchical' and 'max' with set abstraction for local features
  num_hierarchical_levels: 3 # Ignored
  num_centroids: 64

state:
  num_tokens: 8  # 2x2x2 grid
  token_dim: 512 # Match encoder output
  learnable_init: true
  init_scale: 0.1

decoder:
  hidden_dim: 512
  num_layers: 4
  num_heads: 4
  feedforward_dim: 512
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true
  norm_type: 'layer_norm'
  qk_norm: false
  num_register_tokens: 0

ray_encoder:
  pe_type: 'nerf' # TODO: how does renderformer encode rays?
  vertex_pe_num_freqs: 6 # this controls how many frequencies are applied for the pe
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 4
  patch_size: 16
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 512 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  pe_type: 'rope' # TODO:[ROPE] support rope # TODO: KEEP? 
  # TODO: add a obj num_freq term?
  hidden_dim: 512
  num_heads: 4
  num_layers: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'
  pe_type: 'nerf'
  pe_num_freqs: 8
  use_dpt_decoder: true
  dpt_features: 128
  dpt_out_channels: [96, 192, 384, 768] 
  include_alpha: false

training:
  batch_size: 64
  learning_rate: 1.0e-4
  num_epochs: 5000
  warmup_epochs: 500
  save_interval: 100  # for visualization
  checkpoint_interval: 500  # for saving model checkpoint 
  image_res: 256
  data_dir: "data_generation/output_auto/datasets/attempt6_table_chair_540"
  log_dir: "training/logs/attempt6_table_chair_540"
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
