# Training Configuration

# Run notes (changes from last run): 
#     Updated/fixed RoPE implementation in MHA
#     Using 64 local pointnet features (set abstraction: for 2048 points pershape, 64 centroids each feature is avg of 32 points) 

# Model: 
#     Rays now encoded in camera space (so view-dependent stage is now in camera coordinates)
#     Obj positions also transformed to camera space in RadiancePredictor
#     In RayEncoder, remove 2D Patch Positional Encodings, so that encoder matches ViewTransformer of RenderFormer
# Dataset: attempt2_fixed_view
#     data_generation/output/datasets/attempt2_fixed_view
# Hyperparams:
# Training: 
#   Higher epochs, lower resolution to 128
#   Using BF16, LR 1e-4

encoder:
  input_dim: 6  # Position (x,y,z) + Normal (nx,ny,nz)
  hidden_dims: [512, 1024, 2048] # Increase capacity for memorization
  output_dim: 1024 # Increased
  backbone_dim: 768
  pooling_type: 'set_abstraction' # Replaced 'hierarchical' and 'max' with set abstraction for local features
  num_hierarchical_levels: 3 # Ignored
  num_centroids: 64

state:
  num_tokens: 8  # 2x2x2 grid
  token_dim: 1024 # Match encoder output
  learnable_init: true
  init_scale: 0.1

decoder:
  hidden_dim: 1024
  num_layers: 4 # Slightly deeper
  num_heads: 8
  feedforward_dim: 2048
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true
  norm_type: 'layer_norm'
  qk_norm: false
  num_register_tokens: 0
  bias: true
  rope_double_max_freq: false

ray_encoder:
  pe_type: 'nerf' # TODO: how does renderformer encode rays?
  vertex_pe_num_freqs: 8 # this controls how many frequencies are applied for the pe
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 8
  patch_size: 8
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 1024 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  pe_type: 'rope' # TODO:[ROPE] support rope # TODO: KEEP? 
  # TODO: add a obj num_freq term?
  hidden_dim: 1024
  num_heads: 8
  num_layers: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'
  use_dpt_decoder: true

training:
  batch_size: 64
  learning_rate: 1.0e-4
  num_epochs: 500
  save_interval: 50
  image_res: 128
  data_dir: "data_generation/output_auto/datasets/attempt2_fixed_view"
  log_dir: "training/logs"
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
