# Training Configuration
# about 46M param
# Total Parameters: 45,930,062
# Trainable Parameters: 45,930,054
#   pointnet_encoder: 6,637,056 params
#   scene_transformer: 12,617,732 params
#   ray_encoder: 3,540,992 params
#   predictor: 23,134,282 params
#     dpt_head: 6,314,051 params

# Training:
# Model: using new model with no state manager
# -- fixed rope dims, fixed ray dirs in camera space
# Data: rf ds2_chairs1-3_cbox0-3
# 20k epochs, 128x128
# Compare with RF run: renderformer/training/logs/ds2_chairs1-3_cbox0-3/20260623-154203_full_ds_params46M_res128x128

encoder:
  input_dim: 6  # Position (x,y,z) + Normal (nx,ny,nz)
  hidden_dims: [768, 1024, 1536]
  output_dim: 512
  backbone_dim: 512
  property_embed_dim: 128
  pooling_type: 'hierarchical' #'set_abstraction' # Replaced 'hierarchical' and 'max' with set abstraction for local features
  num_hierarchical_levels: 3 # Ignored
  # num_centroids: 64

# state:
#   num_tokens: 8  # 2x2x2 grid
#   token_dim: 512 # Match encoder output
#   learnable_init: true
#   init_scale: 0.1

decoder:
  hidden_dim: 512
  num_layers: 4 
  num_heads: 4
  feedforward_dim: 2048 # 512 * 4??? The number of frequencies in the positional encoding for vertex positions
  dropout: 0.0
  activation: 'gelu'
  return_all_layers: true
  use_self_attention: true # Whether to double the max frequency for RoPE.
  norm_type: 'layer_norm'
  qk_norm: true
  bias: true
  rope_double_max_freq: false
  num_register_tokens: 0

ray_encoder:
  pe_type: 'rope' # ROPE handles spatial position encoding
  vertex_pe_num_freqs: 8 # this controls how many frequencies are applied for the pe
  vdir_pe_type: 'nerf'
  vdir_num_freqs: 4
  patch_size: 16
  norm_type: 'layer_norm'
  view_transformer_latent_dim: 512 # Must match predictor hidden_dim
  view_transformer_n_heads: 4

predictor:
  # TODO: add a obj num_freq term?
  hidden_dim: 512
  num_layers: 4
  num_heads: 4
  dropout: 0
  activation: 'gelu'
  norm_type: 'layer_norm'
  pe_type: 'rope' # <-- TODO: take this out of the predictor section? since it also applies for decoder
  pe_num_freqs: 8 # is this redunant to vertex_pe_num_freqs? TODO: figure this out 
  use_dpt_decoder: true
  dpt_features: 128
  dpt_out_channels: [64, 128, 256, 512] 
  include_alpha: false

training:
  batch_size: 64
  learning_rate: 1.0e-4
  num_epochs: 5 #20000
  warmup_epochs: 2000
  save_interval: 250  # for visualization
  checkpoint_interval: 2000  # for saving model checkpoint 
  image_res: 128
  data_dir: "renderformer/datasets/processed_datasets/ds2_chairs1-3_cbox0-3"
  log_dir: "training/logs/rf_ds2_chairs1-3_cbox0-3"
  run_name: "throwaway_run_for_package" # Optional string tag for log dir name
  # max_dataset_size: 4   # Optional max samples for dataset. If not specified, uses whole dataset
  # shuffle_data: true
  # shuffle_data_seed: 43
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
  use_amp: True
  use_compile: False
  package_model: True
  num_workers: 16